spring.application.name=transfert-etudiant
server.port=8080

# PostgreSQL (adaptez username/password si nécessaire)
spring.datasource.url=jdbc:postgresql://localhost:5432/transfert_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA – ne PAS spécifier de dialecte (auto-détection)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# CORS (pour React)
cors.allowed.origins=http://localhost:1420

# Logging
logging.level.com.transfert=DEBUG