# ===================================================================
# CONFIGURATION DE LA BASE DE DONNÉES (POSTGRESQL)
# ===================================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/transfert_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURATION HIBERNATE / JPA
# ===================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# CONFIGURATION DU PORT
# ===================================================================
server.port=${PORT:8080}

# ===================================================================
# CONFIGURATION SECURITE & CORS (CORRECTION ICI 🚀)
# ===================================================================
# Spring lira la variable FRONTEND_URL de Render. En local, il prendra http://localhost:5173
cors.allowed.origins=${FRONTEND_URL:http://localhost:1420}

# Si ton JwtAuthenticationFilter utilise une clé secrète, on lui donne une valeur par défaut ici :
jwt.secret=${JWT_SECRET:maCleSecreteSuperLongueEtSecuriseePourLeDevLocal123456!}